SELECT USERENV('language') FROM DUAL
;
--AMERICAN_AMERICA.WE8ISO8859P1
--TRADITIONAL CHINESE_TAIWAN.ZHT16MSWIN950
--WE8ISO8859P15
--server???
SELECT * FROM NLS_DATABASE_PARAMETERS
;
--client???
SELECT * FROM V$NLS_PARAMETERS
;
select CONVERT( '??' USING utf8) from dual
;
select CONVERT ( '??', 'AL32UTF8', 'WE8ISO8859P1') from dual
;
SELECT '??'  FROM  DUAL
;
SELECT * FROM NLS_DATABASE_PARAMETERS
WHERE PARAMETER LIKE '%CHARACTERSET'
;
SELECT * FROM  V$NLS_PARAMETERS
WHERE PARAMETER LIKE '%CHARACTERSET'
;
--Server
select tab1.aa || '_' || tab2.bb || '.' || tab3.cc
  from (select VALUE$ aa from sys.props$ where name = 'NLS_LANGUAGE') tab1,
       (SELECT VALUE$ BB FROM SYS.PROPS$ WHERE NAME = 'NLS_ISO_CURRENCY') TAB2,
       (SELECT VALUE$ CC FROM SYS.PROPS$ WHERE NAME = 'NLS_CHARACTERSET') TAB3
;
--???? dmp ??????
 SELECT NLS_CHARSET_NAME(TO_NUMBER('0354','xxxx')) FROM DUAL
 ;
 
 --??
 --CONVERT( '??', 'To_???', 'From_???' )
 
--CONVERT( '??', 'To_???' )
;
/**  ????  ?**/
 --iso-8859-1  WE8ISO8859P1
--MS950   ZHT16MSWIN950
--UTF8  AL32UTF8
--big5  ZHT16BIG5
;
--清理資料
TRUNCATE TABLE HUR_DATA_USAGE
;
TRUNCATE TABLE HUR_CURRENT 
;
TRUNCATE TABLE HUR_CURRENT_DAY
;
UPDATE HUR_DATA_USAGE A
SET A.CHARGE = NULL
;
Update HUR_CURRENT A
set A.LAST_FILEID=0
;
--查詢門號 IMSI
SELECT B.IMSI,A.SERVICECODE,A.PRICEPLANID,A.SUBSIDIARYID,A.SERVICEID,
(CASE A. STATUS WHEN '1' then to_char(C.value) when '3' then to_char( C.value) when '10' then to_char(C.value) else null end) NCODE 
FROM SERVICE A,IMSI B,PARAMETERVALUE C 
WHERE A.SERVICEID=B.SERVICEID AND A.SERVICECODE IS NOT NULL 
AND B.SERVICEID=C.SERVICEID(+) AND C.PARAMETERVALUEID(+)=3748
AND B.IMSI=454120260211541
;
SELECT *
FROM HUR_CURRENT A
WHERE A.IMSI =454120260228157
;
--華人上網包
SELECT A.S2TIMSI IMSI,A.S2TMSISDN MSISDN,A.SERVICECODE,A.STARTDATE,A.ENDDATE 
FROM ADDONSERVICE_N A 
WHERE A.S2TMSISDN = 85269477897

--WHERE A.S2TIMSI = 454120260228157
;
SELECT *
FROM ADDONSERVICE A 
WHERE A.S2TMSISDN = 85269477897
;
--比對CDR的每日批價正確性
SELECT A.IMSI,A.MCCMNC,A.DAY, A.CHARGE, B.CHARGE
FROM HUR_CURRENT_DAY A,
(SELECT A.IMSI,A.MCCMNC,to_char(to_date(A.CALLTIME,'yyyy/mm/dd hh24:mi:ss'),'yyyymmdd') daytime,Sum(A.CHARGE) CHARGE
FROM HUR_DATA_USAGE A
GROUP BY A.IMSI,A.MCCMNC, TO_CHAR(TO_DATE(A.CALLTIME,'yyyy/mm/dd hh24:mi:ss'),'yyyymmdd'))
B
WHERE A.IMSI = B.IMSI AND A.MCCMNC=B.MCCMNC AND A.DAY=B.DAYTIME AND A.CHARGE<>B.CHARGE AND A.day=20150104
order by A.DAY desc
;
--比較日累計與月累計
SELECT A.IMSI,A.MONTH,A.CHARGE,B.CHARGE
FROM HUR_CURRENT A,
(SELECT IMSI,SUBSTR(day,0,6) mon,sum(charge) charge
FROM HUR_CURRENT_DAY 
GROUP BY IMSI,SUBSTR(DAY,0,6) ) B
WHERE A.IMSI=B.IMSI AND A.MONTH=B.MON
AND A.CHARGE<>B.CHARGE
;
--換卡記錄 IMSI SERVICEID
SELECT A.NEWVALUE IMSI, C.SERVICEID 
				FROM SERVICEINFOCHANGEORDER A, SERVICEORDER B, SERVICE C ,(
				        SELECT max(A.COMPLETEDATE) COMPLETEDATE, A.NEWVALUE,count(1) 
				        FROM SERVICEINFOCHANGEORDER A 
				        WHERE A.FIELDID=3713  AND A.COMPLETEDATE IS NOT NULL 
				        AND A.OLDVALUE <> A.NEWVALUE 
				        GROUP BY A.NEWVALUE ) D 
				WHERE A.FIELDID=3713 AND A.ORDERID=B.ORDERID 
				AND B.SERVICEID=C.SERVICEID 
				AND A.OLDVALUE <> A.NEWVALUE 
				AND D.COMPLETEDATE=A.COMPLETEDATE 
				AND A.NEWVALUE=D.NEWVALUE 
				AND A.NEWVALUE IN ( SELECT A.IMSI FROM IMSI A WHERE A.SERVICEID IS NULL)
        ;
  --完整的IMSI SERVICEID
     SELECT B.IMSI,A.SERVICEID
FROM SERVICE A,IMSI B,PARAMETERVALUE C 
WHERE A.SERVICEID=B.SERVICEID AND A.SERVICECODE IS NOT NULL 
AND B.SERVICEID=C.SERVICEID(+) AND C.PARAMETERVALUEID(+)=3748
UNION
SELECT A.NEWVALUE IMSI, C.SERVICEID 
				FROM SERVICEINFOCHANGEORDER A, SERVICEORDER B, SERVICE C ,(
				        SELECT max(A.COMPLETEDATE) COMPLETEDATE, A.NEWVALUE,count(1) 
				        FROM SERVICEINFOCHANGEORDER A 
				        WHERE A.FIELDID=3713  AND A.COMPLETEDATE IS NOT NULL 
				        AND A.OLDVALUE <> A.NEWVALUE 
				        GROUP BY A.NEWVALUE ) D 
				WHERE A.FIELDID=3713 AND A.ORDERID=B.ORDERID 
				AND B.SERVICEID=C.SERVICEID 
				AND A.OLDVALUE <> A.NEWVALUE 
				AND D.COMPLETEDATE=A.COMPLETEDATE 
				AND A.NEWVALUE=D.NEWVALUE 
				AND A.NEWVALUE IN ( SELECT A.IMSI FROM IMSI A WHERE A.SERVICEID IS NULL)
        ;
  --分解IP
  SELECT 
        SUBSTR(:IP,1,INSTR(:IP, '.',1,1)-1) A,
        SUBSTR(:IP,INSTR(:IP, '.',1,1)+1,INSTR(:IP, '.',1,2)-INSTR(:IP, '.',1,1)-1) B,
        SUBSTR(:IP,INSTR(:IP, '.',1,2)+1,INSTR(:IP, '.',1,3)-INSTR(:IP, '.',1,2)-1) C,
        SUBSTR(:IP,INSTR(:IP, '.',1,3)+1) D
        FROM DUAL
        ;
        
--voice mail
       SELECT b.servicecode
FROM SERVICEPARAMETER a, service b
WHERE a.serviceid=b.serviceid AND a.parameterid=3720 
  AND b.priceplanid=139 AND b.status IN (1,3)
ORDER BY b.servicecode

;
--IMSI資料
SELECT * FROM (
SELECT c.serviceid, c.servicecode, '' OldIMSI, a.fieldvalue NewIMSI, b.COMPLETEDATE, b.orderid, 'New' OrderType
FROM NEWSERVICEORDERINFO a, serviceorder b, service c
WHERE a.fieldid=3713 AND a.orderid=b.orderid
  AND b.serviceid=c.serviceid
  AND TO_CHAR(c.dateactivated,'yyyymmdd')>='20070205'
  AND TO_CHAR(b.completedate,'yyyymmdd')>='20070205'
UNION ALL
SELECT c.SERVICEID, C.servicecode, a.oldvalue OldIMSI, A.NEWVALUE imsi, A.COMPLETEDATE, b.orderid, 'Change' OrderType
FROM SERVICEINFOCHANGEORDER A, SERVICEORDER B, SERVICE C 
WHERE A.FIELDID=3713 AND A.ORDERID=B.ORDERID
  AND B.SERVICEID=C.SERVICEID
  AND TO_CHAR(c.dateactivated,'yyyymmdd')>='20070205'
  AND TO_CHAR(a.completedate,'yyyymmdd')>='20070205'
  AND a.oldvalue <> a.newvalue
) ORDER BY SERVICEID, ORDERID
;
--IMSI資料2   找出此SERVICE ID最新IMSI
SELECT A.SERVICEID,A.IMSI
FROM(
SELECT A.SERVICEID,B.NEWVALUE IMSI,A.COMPLETEDATE
FROM SERVICEORDER A,SERVICEINFOCHANGEORDER B
WHERE A.ORDERID =B.ORDERID AND  B.FIELDID=3713
UNION
SELECT A.SERVICEID,B.FIELDVALUE IMSI,A.COMPLETEDATE
FROM SERVICEORDER A,NEWSERVICEORDERINFO B
WHERE A.ORDERID =B.ORDERID AND   B.FIELDID=3713 )A,
(SELECT SERVICEID,MAX(COMPLETEDATE) COMPLETEDATE
  from(SELECT A.SERVICEID,B.NEWVALUE,A.COMPLETEDATE
            FROM SERVICEORDER A,SERVICEINFOCHANGEORDER B
            WHERE A.ORDERID =B.ORDERID AND  B.FIELDID=3713
            UNION
            SELECT A.SERVICEID,B.FIELDVALUE,A.COMPLETEDATE
            FROM SERVICEORDER A,NEWSERVICEORDERINFO B
            WHERE A.ORDERID =B.ORDERID AND   B.FIELDID=3713)
  GROUP BY SERVICEID )B
WHERE A.SERVICEID=B.SERVICEID AND A.COMPLETEDATE =B.COMPLETEDATE 
;
--IMSI資料3  找出此IMSI最後使用的SERVICEID
 SELECT A.SERVICEID,A.IMSI
          FROM(
                        SELECT A.SERVICEID,B.NEWVALUE IMSI,A.COMPLETEDATE
                        FROM SERVICEORDER A,SERVICEINFOCHANGEORDER B
                        WHERE A.ORDERID =B.ORDERID AND  B.FIELDID=3713
                        UNION
                        SELECT A.SERVICEID,B.FIELDVALUE IMSI,A.COMPLETEDATE
                        FROM SERVICEORDER A,NEWSERVICEORDERINFO B
                        WHERE A.ORDERID =B.ORDERID AND   B.FIELDID=3713 )A,
                                                                                                  (SELECT IMSI,MAX(COMPLETEDATE) COMPLETEDATE
                                                                                                    from(SELECT A.SERVICEID,B.NEWVALUE IMSI,A.COMPLETEDATE
                                                                                                              FROM SERVICEORDER A,SERVICEINFOCHANGEORDER B
                                                                                                              WHERE A.ORDERID =B.ORDERID AND  B.FIELDID=3713
                                                                                                              UNION
                                                                                                              SELECT A.SERVICEID,B.FIELDVALUE IMSI,A.COMPLETEDATE
                                                                                                              FROM SERVICEORDER A,NEWSERVICEORDERINFO B
                                                                                                              WHERE A.ORDERID =B.ORDERID AND   B.FIELDID=3713)
                                                                                                    GROUP BY IMSI )B
              WHERE A.IMSI=B.IMSI AND A.COMPLETEDATE =B.COMPLETEDATE
              and A.imsi ='454120260230385'
        ;
        SELECT A.USAGEID,
SUBSTR(A.SGSNADDRESS,1,INSTR(A.SGSNADDRESS, '.',1,1)-1)*256*256*256+
        SUBSTR(A.SGSNADDRESS,INSTR(A.SGSNADDRESS, '.',1,1)+1,INSTR(A.SGSNADDRESS, '.',1,2)-INSTR(A.SGSNADDRESS, '.',1,1)-1) *256*256+
        SUBSTR(A.SGSNADDRESS,INSTR(A.SGSNADDRESS, '.',1,2)+1,INSTR(A.SGSNADDRESS, '.',1,3)-INSTR(A.SGSNADDRESS, '.',1,2)-1) *256+
        SUBSTR(A.SGSNADDRESS,INSTR(A.SGSNADDRESS, '.',1,3)+1) SUM,A.MCCMNC,A.CALLTIME
FROM HUR_DATA_USAGE A
;
--查詢lock
select object_name, s.sid, s.serial#, p.spid 
from v$locked_object l, dba_objects o, v$session s, v$process p
where l.object_id = o.object_id and l.session_id = s.sid and s.paddr = p.addr
;
--解lock
ALTER SYSTEM KILL SESSION 'sid,serial#'
;